spring.datasource.url=jdbc:mysql://localhost:3306/employeeDb
server.port = 8080
department.service.url= http://localhost:8081/api/department
personal.url = http://localhost:8082/api/person
spring.datasource.username=root
spring.datasource.password=Manja@918273

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect